export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";

export const UPDATE_TEXT_COLOR = "UPDATE_TEXT_COLOR";
export const UPDATE_BACKGROUND_COLOR = "UPDATE_BACKGROUND_COLOR";
export const UPDATE_FAVORITE_CITY = "UPDATE_FAVORITE_CITY";