const actionTypes = {
  ADD_EVENT: "ADD_EVENT",
  REMOVE_EVENT: "REMOVE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  MARK_FAVORITE_EVENT: "MARK_FAVORITE_EVENT",
  UNMARK_FAVORITE_EVENT: "UNMARK_FAVORITE_EVENT"
};

export default actionTypes;